In [6]:
import pandas as pd
from datetime import datetime

# Load the CSV file into a DataFrame
df = pd.read_csv('awards.csv')

# Convert the 'date_employed' column to datetime
df['date_employed'] = pd.to_datetime(df['date_employed'])

# Calculate the number of years spent as of the current date
current_date = datetime.now()
df['years_spent'] = (current_date - df['date_employed']).dt.days // 365

# Define the target years you want to check
target_years = [10, 15, 20, 25, 30]

# Create a result DataFrame with columns for each target year
result_df = pd.DataFrame({'Company': df['company'], 'Full Name': df['full_name']})

# Calculate the count of people who have spent exactly X years by 2024 for each X in target_years
for years in target_years:
    result_df[f'{years} Years'] = df['years_spent'] == years

# Display the result DataFrame
print(result_df)

    Company                 Full Name  10 Years  15 Years  20 Years  25 Years  \
0       ACC         Jacob Tetteh-Cole     False     False     False     False
1   SERVICE   Christopher Kwaku Ayika     False     False     False     False
2       ACE         Ernest Gyimah Adu     False     False     False     False
3       ACE        Philip Laryea Doku     False     False     False     False
4   SERVICE              James Amoako     False     False     False     False
..      ...                       ...       ...       ...       ...       ...
76  SERVICE  Raphael Kwaku Agbelengor     False     False     False     False
77      ACE              Bernice Kumi     False     False     False     False
78  SERVICE          Jewel Ama Mensah     False     False     False      True
79      ACE            Gillian Okyere     False     False     False     False
80      ACC            Albert Boateng     False     False     False     False

    30 Years
0      False
1      False
2      False
3      False
4      False
..       ...
76     False
77     False
78     False
79     False
80     False

[81 rows x 7 columns]

In [7]:
import pandas as pd
from datetime import datetime

# Load the CSV file into a DataFrame
df = pd.read_csv('awards.csv')

# Convert the 'date_employed' column to datetime
df['date_employed'] = pd.to_datetime(df['date_employed'])

# Calculate the number of years spent as of the current date
current_date = datetime.now()
df['years_spent'] = (current_date - df['date_employed']).dt.days // 365

# Create a result DataFrame with a column for the number of people who have spent exactly 10 years by 2024
result_df = pd.DataFrame({'Company': df['company'], 'Full Name': df['full_name']})

# Calculate whether each person has spent exactly 10 years by 2024
result_df['10 Years'] = df['years_spent'] == 10

# Count the number of people who have spent exactly 10 years
count_10_years = sum(result_df['10 Years'])

# Print the count
print(f"Number of people who have spent exactly 10 years by 2024: {count_10_years}")

Number of people who have spent exactly 10 years by 2024: 8

In [8]:
result_df

    Company                 Full Name  10 Years
0       ACC         Jacob Tetteh-Cole     False
1   SERVICE   Christopher Kwaku Ayika     False
2       ACE         Ernest Gyimah Adu     False
3       ACE        Philip Laryea Doku     False
4   SERVICE              James Amoako     False
..      ...                       ...       ...
76  SERVICE  Raphael Kwaku Agbelengor     False
77      ACE              Bernice Kumi     False
78  SERVICE          Jewel Ama Mensah     False
79      ACE            Gillian Okyere     False
80      ACC            Albert Boateng     False

[81 rows x 3 columns]

In [9]:
import pandas as pd
from datetime import datetime

# Load the CSV file into a DataFrame
df = pd.read_csv('awards.csv')

# Convert the 'date_employed' column to datetime
df['date_employed'] = pd.to_datetime(df['date_employed'])

# Calculate the number of years spent as of the current date
current_date = datetime.now()
df['years_spent'] = (current_date - df['date_employed']).dt.days // 365

# Create a result DataFrame with columns for company, full name, and years spent
result_df = pd.DataFrame({'Company': df['company'], 'Full Name': df['full_name'], 'Years Spent': df['years_spent']})

# Filter the DataFrame to select only people who have spent exactly 10 years by 2024
exact_10_years_df = result_df[result_df['Years Spent'] == 10]

# Print the names of people who have spent exactly 10 years by 2024 along with their respective companies
for index, row in exact_10_years_df.iterrows():
    print(f"Company: {row['Company']}, Full Name: {row['Full Name']}")

Company: ACC, Full Name: Roger Baah
Company: ACC, Full Name: Alex Akondoh
Company: SERVICE, Full Name: Anita Gyekyewaa Adu - Yeboah
Company: ACC, Full Name: Theresa Hanson
Company: AIHCL, Full Name: Alexander Kwabena Acheampong
Company: ACC, Full Name: Abner Prado Salazar
Company: ACC, Full Name: Ernest Kwaakoh Essuman
Company: SERVICE, Full Name: Sarah Buabeng

In [10]:
import pandas as pd
from datetime import datetime

# Load the CSV file into a DataFrame
df = pd.read_csv('awards.csv')

# Convert the 'date_employed' column to datetime
df['date_employed'] = pd.to_datetime(df['date_employed'])

# Calculate the number of years spent as of the current date
current_date = datetime.now()
df['years_spent'] = (current_date - df['date_employed']).dt.days // 365

# Create a result DataFrame with columns for company, full name, and years spent
result_df = pd.DataFrame({'Company': df['company'], 'Full Name': df['full_name'], 'Years Spent': df['years_spent']})

# Filter the DataFrame to select only people who have spent exactly 15 years by 2024
exact_15_years_df = result_df[result_df['Years Spent'] == 15]

# Print the names of people who have spent exactly 15 years by 2024 along with their respective companies
for index, row in exact_15_years_df.iterrows():
    print(f"Company: {row['Company']}, Full Name: {row['Full Name']}")

Company: ACC, Full Name: Ephraim Antwi Agyei
Company: ACC, Full Name: Albert Danso
Company: SERVICE, Full Name: Bright Akosua Senam Agudze
Company: ACE, Full Name: Ohenenana Kwaku Ofosuhene-Apenteng

In [11]:
import pandas as pd
from datetime import datetime

# Load the CSV file into a DataFrame
df = pd.read_csv('awards.csv')

# Convert the 'date_employed' column to datetime
df['date_employed'] = pd.to_datetime(df['date_employed'])

# Calculate the number of years spent as of the current date
current_date = datetime.now()
df['years_spent'] = (current_date - df['date_employed']).dt.days // 365

# Create a result DataFrame with columns for company, full name, and years spent
result_df = pd.DataFrame({'Company': df['company'], 'Full Name': df['full_name'], 'Years Spent': df['years_spent']})

# Filter the DataFrame to select only people who have spent exactly 20 years by 2024
exact_20_years_df = result_df[result_df['Years Spent'] == 20]

# Print the names of people who have spent exactly 20 years by 2024 along with their respective companies
for index, row in exact_20_years_df.iterrows():
    print(f"Company: {row['Company']}, Full Name: {row['Full Name']}")

Company: SERVICE, Full Name: Ellen Agbemafo
Company: AIHCL, Full Name: Michael Wuddah-Martey

In [14]:
import pandas as pd

# Load the CSV file into a DataFrame
df = pd.read_csv('awards.csv')

# Convert the 'date_employed' column to datetime using 'month/day/year' format
df['date_employed'] = pd.to_datetime(df['date_employed'], format='%m/%d/%Y')

# Calculate the number of years spent in the company by 2024
target_year = 2024
df['years_spent'] = target_year - df['date_employed'].dt.year

# Define the years you want to check
target_years = [10, 15, 20, 25, 30]

# Create a result DataFrame with columns for company, full name, and years spent
result_df = pd.DataFrame({'Company': df['company'], 'Full Name': df['full_name'], 'Years Spent': df['years_spent']})

# Loop through the target years and print the names of people who have spent exactly those years by 2024
for years in target_years:
    exact_years_df = result_df[result_df['Years Spent'] == years]
    print(f"People with exactly {years} years of employment by 2024:")
    for index, row in exact_years_df.iterrows():
        print(f"Company: {row['Company']}, Full Name: {row['Full Name']}")
    print()

People with exactly 10 years of employment by 2024:
Company: ACC, Full Name: Ernest Kwame
Company: ACC, Full Name: Foster Nortey
Company: AIHCL, Full Name: Ishmael Akwasi Osei
Company: AIHCL, Full Name: Faustina Osei-Tutu
Company: ACE, Full Name: Isaac Twumasi
Company: ACE, Full Name: Thywill Seshie Jiagge
Company: ACC, Full Name: Silas Adu

People with exactly 15 years of employment by 2024:
Company: ACE, Full Name: Naana Pokua Manu
Company: SERVICE, Full Name: Samuel Ahenkorah
Company: ACC, Full Name: Kwaku Asiedu-Boateng

People with exactly 20 years of employment by 2024:
Company: ACC, Full Name: Samuel Sokah
Company: SERVICE, Full Name: Muniru Zakari
Company: ACC, Full Name: Joyce Naa Odey Abbey

People with exactly 25 years of employment by 2024:

People with exactly 30 years of employment by 2024:

In [17]:
import pandas as pd

# Load the CSV file into a DataFrame
df = pd.read_csv('awards.csv')

# Convert the 'date_employed' column to datetime using 'month/day/year' format
df['date_employed'] = pd.to_datetime(df['date_employed'], format='%m/%d/%Y')

# Calculate the number of years spent in the company by 2024
target_year = 2024
df['years_spent'] = target_year - df['date_employed'].dt.year

# Define the years you want to check
target_years = [10, 15, 20, 25, 30]

# Create a result DataFrame with columns for company, full name, and years spent
result_df = pd.DataFrame({'Company': df['company'], 'Full Name': df['full_name'], 'Years Spent': df['years_spent']})

# Loop through the target years and print the names of people who have spent exactly those years by 2024
for years in target_years:
    exact_years_df = result_df[result_df['Years Spent'] == years]
    count_exact_years = len(exact_years_df)  # Count the total number of people in each target year
    print(f"People with exactly {years} years of employment by 2024 ({count_exact_years} people):")
    for index, row in exact_years_df.iterrows():
        print(f"Company: {row['Company']}, Full Name: {row['Full Name']}")
    print()

People with exactly 10 years of employment by 2024 (7 people):
Company: ACC, Full Name: Ernest Kwame
Company: ACC, Full Name: Foster Nortey
Company: AIHCL, Full Name: Ishmael Akwasi Osei
Company: AIHCL, Full Name: Faustina Osei-Tutu
Company: ACE, Full Name: Isaac Twumasi
Company: ACE, Full Name: Thywill Seshie Jiagge
Company: ACC, Full Name: Silas Adu

People with exactly 15 years of employment by 2024 (3 people):
Company: ACE, Full Name: Naana Pokua Manu
Company: SERVICE, Full Name: Samuel Ahenkorah
Company: ACC, Full Name: Kwaku Asiedu-Boateng

People with exactly 20 years of employment by 2024 (3 people):
Company: ACC, Full Name: Samuel Sokah
Company: SERVICE, Full Name: Muniru Zakari
Company: ACC, Full Name: Joyce Naa Odey Abbey

People with exactly 25 years of employment by 2024 (0 people):

People with exactly 30 years of employment by 2024 (0 people):

In [20]:
import pandas as pd

# Load the CSV file into a DataFrame
df = pd.read_csv('awards.csv')

# Convert the 'date_employed' column to datetime using 'month/day/year' format
df['date_employed'] = pd.to_datetime(df['date_employed'], format='%m/%d/%Y')

# Calculate the number of years spent in the company by 2024
target_year = 2024
df['years_spent'] = target_year - df['date_employed'].dt.year

# Define the years you want to check
target_years = [10, 15, 20, 25, 30]

# Create a result DataFrame with columns for company, full name, and years spent
result_df = pd.DataFrame({'Company': df['company'], 'Full Name': df['full_name'], 'Years Spent': df['years_spent']})

# Loop through the target years and print the names of people who have spent exactly those years by 2024
for years in target_years:
    exact_years_df = result_df[result_df['Years Spent'] == years]
    count_exact_years = len(exact_years_df)  # Count the total number of people in each target year
    print(f"People with exactly {years} years of employment by 2024 ({count_exact_years} people):")
    for index, row in exact_years_df.iterrows():
        print(f"Company: {row['Company']}, Full Name: {row['Full Name']}")
    print()

# Convert the result_df to an Excel file with the name 'awards.xlsx'
result_df.to_excel('awards.xlsx', index=False)

People with exactly 10 years of employment by 2024 (7 people):
Company: ACC, Full Name: Ernest Kwame
Company: ACC, Full Name: Foster Nortey
Company: AIHCL, Full Name: Ishmael Akwasi Osei
Company: AIHCL, Full Name: Faustina Osei-Tutu
Company: ACE, Full Name: Isaac Twumasi
Company: ACE, Full Name: Thywill Seshie Jiagge
Company: ACC, Full Name: Silas Adu

People with exactly 15 years of employment by 2024 (3 people):
Company: ACE, Full Name: Naana Pokua Manu
Company: SERVICE, Full Name: Samuel Ahenkorah
Company: ACC, Full Name: Kwaku Asiedu-Boateng

People with exactly 20 years of employment by 2024 (3 people):
Company: ACC, Full Name: Samuel Sokah
Company: SERVICE, Full Name: Muniru Zakari
Company: ACC, Full Name: Joyce Naa Odey Abbey

People with exactly 25 years of employment by 2024 (0 people):

People with exactly 30 years of employment by 2024 (0 people):

In [22]:
import pandas as pd

# Load the CSV file into a DataFrame
df = pd.read_csv('awards.csv')

# Convert the 'date_employed' column to datetime using 'month/day/year' format
df['date_employed'] = pd.to_datetime(df['date_employed'], format='%m/%d/%Y')

# Calculate the number of years spent in the company by 2024
target_year = 2024
df['years_spent'] = target_year - df['date_employed'].dt.year

# Define the years you want to check
target_years = [10, 15, 20, 25, 30]

# Create a result DataFrame with columns for company, full name, and years spent
result_df = pd.DataFrame({'Company': df['company'], 'Full Name': df['full_name'], 'Years Spent': df['years_spent']})

# Loop through the target years and print the names of people who have spent exactly those years by 2024
for years in target_years:
    exact_years_df = result_df[result_df['Years Spent'] == years]
    count_exact_years = len(exact_years_df)  # Count the total number of people in each target year
    print(f"People with exactly {years} years of employment by 2024 ({count_exact_years} people):")
    for index, row in exact_years_df.iterrows():
        print(f"Company: {row['Company']}, Full Name: {row['Full Name']}")
    print()

# Convert the result_df to an Excel file with the name 'awards.xlsx'
result_df.to_excel('awards.xlsx', index=False)

People with exactly 10 years of employment by 2024 (7 people):
Company: ACC, Full Name: Ernest Kwame
Company: ACC, Full Name: Foster Nortey
Company: AIHCL, Full Name: Ishmael Akwasi Osei
Company: AIHCL, Full Name: Faustina Osei-Tutu
Company: ACE, Full Name: Isaac Twumasi
Company: ACE, Full Name: Thywill Seshie Jiagge
Company: ACC, Full Name: Silas Adu

People with exactly 15 years of employment by 2024 (3 people):
Company: ACE, Full Name: Naana Pokua Manu
Company: SERVICE, Full Name: Samuel Ahenkorah
Company: ACC, Full Name: Kwaku Asiedu-Boateng

People with exactly 20 years of employment by 2024 (3 people):
Company: ACC, Full Name: Samuel Sokah
Company: SERVICE, Full Name: Muniru Zakari
Company: ACC, Full Name: Joyce Naa Odey Abbey

People with exactly 25 years of employment by 2024 (0 people):

People with exactly 30 years of employment by 2024 (0 people):